2020-01-08 14:43:51,769 ERROR: Exception on /user_stats [GET] [in /Users/danielvaroli/Desktop/personal_website/workout_app/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/danielvaroli/Desktop/personal_website/workout_app/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/danielvaroli/Desktop/personal_website/workout_app/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/danielvaroli/Desktop/personal_website/workout_app/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/danielvaroli/Desktop/personal_website/workout_app/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/danielvaroli/Desktop/personal_website/workout_app/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/danielvaroli/Desktop/personal_website/workout_app/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/danielvaroli/Desktop/personal_website/workout_app/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/danielvaroli/Desktop/personal_website/workout_app/app/main/routes.py", line 148, in user_stats
    return render_template('user_stats.html', users = users, num_users=num_users, total_visits=total_visits)
  File "/Users/danielvaroli/Desktop/personal_website/workout_app/venv/lib/python3.7/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/danielvaroli/Desktop/personal_website/workout_app/venv/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/danielvaroli/Desktop/personal_website/workout_app/venv/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/danielvaroli/Desktop/personal_website/workout_app/venv/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/danielvaroli/Desktop/personal_website/workout_app/venv/lib/python3.7/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/Users/danielvaroli/Desktop/personal_website/workout_app/venv/lib/python3.7/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/Users/danielvaroli/Desktop/personal_website/workout_app/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/danielvaroli/Desktop/personal_website/workout_app/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/danielvaroli/Desktop/personal_website/workout_app/app/templates/user_stats.html", line 1, in template
    {% extend 'base.html' %}
  File "/Users/danielvaroli/Desktop/personal_website/workout_app/venv/lib/python3.7/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/Users/danielvaroli/Desktop/personal_website/workout_app/venv/lib/python3.7/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/Users/danielvaroli/Desktop/personal_website/workout_app/venv/lib/python3.7/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/Users/danielvaroli/Desktop/personal_website/workout_app/venv/lib/python3.7/site-packages/jinja2/parser.py", line 144, in parse_statement
    self.fail_unknown_tag(token.value, token.lineno)
  File "/Users/danielvaroli/Desktop/personal_website/workout_app/venv/lib/python3.7/site-packages/jinja2/parser.py", line 97, in fail_unknown_tag
    return self._fail_ut_eof(name, self._end_token_stack, lineno)
  File "/Users/danielvaroli/Desktop/personal_website/workout_app/venv/lib/python3.7/site-packages/jinja2/parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "/Users/danielvaroli/Desktop/personal_website/workout_app/venv/lib/python3.7/site-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'extend'.
2020-01-08 14:46:15,274 INFO: Workout App startup [in /Users/danielvaroli/Desktop/personal_website/workout_app/app/__init__.py:74]
2020-01-08 14:46:50,371 INFO: Workout App startup [in /Users/danielvaroli/Desktop/personal_website/workout_app/app/__init__.py:74]
